apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recommendations
  namespace: app
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: recs.127.0.0.1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recommendations
                port:
                  number: 80
