---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: recommendations
spec:
  to:
    kind: Service
    name: recommendations
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
